### ISSUE TITLE
Integrating with CocoaPods triggers warning in Xcode 6 Beta

### ISSUE THREAD

**Issue by Legoless** [orta/ARAnalytics#101]
When ARAnalytics is installed with CocoaPods, 2 warnings are generated in Xcode by default.

```
Pods/Pods.xcodeproj Update to recommended settings
- Target 'Pods-ARAnalytics' - Remove Duplicate References in Build Phase
The Compile Sources build phase contains duplicate references for one or more files. This will remove the duplicate file references.
- Target 'Pods-ARAnalytics' - Remove Duplicate References in Build Phase
The Compile Sources build phase contains duplicate references for one or more files. This will remove the duplicate file references.
```

Apparently few files get included multiple times into compile sources, which are:
- ARAnalyticalProvider.m
- ARAnalytics.m
- ARNavigationControllerDelegateProxy.m

Xcode will fix this for us, but having this fixed would be even better. I am assuming this happens only when two subspecs of Analytics are included, for example in my case:

```
pod 'ARAnalytics/Crashlytics'
pod 'ARAnalytics/GoogleAnalytics'
pod 'ARAnalytics/DSL'
```

**Comment by orta** [comment]
This is probably solved
