### ISSUE TITLE
Crashlytics dependency

### ISSUE THREAD

**Issue by ssuchanowski** [orta/ARAnalytics#105]
Could we add dependency to 'CrashlyticsFramework'?

**Comment by sodastsai** [comment]
So now `Crashlytics` has pushed their official Podspec, could we assign it as required dependency?

For Podfile like
```ruby
use_frameworks!
pod 'ARAnalytics', :subspecs => ['Crashlytics']
```
This is necessary (Since the built `ARAnalytics.framework` does require `Crashlytics.framework`)

**Comment by orta** [comment]
for sure
