### ISSUE TITLE
Update Crashlytics provider to initializing without key when using latest Fabric.io based Framework

### ISSUE THREAD

**Issue by glentregoning** [orta/ARAnalytics#114]
The latest Crashlytics Framework (bundled as a part of Fabric.io) automatically auto provisions and configures its keys.

It would be great to update ARAnalytics to support this configuration option.

**Comment by BohdanOrlov** [comment]
Added in #156

**Comment by goktugyil** [comment]
close?

**Comment by orta** [comment]
Yes, thanks @goktugyil
