### ISSUE TITLE
Dropping iOS 6.0 support

### ISSUE THREAD

**Issue by ekurutepe** [orta/ARAnalytics#118]
I am working on integrating Intercom as an analytics provider but Intercom 2.0.5 pod needs iOS 7.0 or higher. 

What do you think about dropping iOS 6 support from ARAnalytics? 

Or is there a way to dynamically determine the deployment target in the podspec by looking at the required system version of each included supspec? Does that even make sense?

**Comment by orta** [comment]
This is done.
