### ISSUE TITLE
Move to RAC for DSL subspec

### ISSUE THREAD

**Issue by ashfurrow** [orta/ARAnalytics#122]
The Aspects library we're using now doesn't support multiple injections per class hierarchy. We've been using the ReactiveCocoa solution in production for six months – may as well move over to it in master. 

Related to https://github.com/orta/ARAnalytics/issues/120

**Comment by sdgandhi** [comment]
What branch is the RAC solution in?

**Comment by ashfurrow** [comment]
Ah, my apologies for not including that. The current fix is on the [ashfurrow-temporary-dsl-fix](https://github.com/orta/ARAnalytics/tree/ashfurrow-temporary-dsl-fix) branch. More information about how to use it and our workaround is available [here](http://artsy.github.io/blog/2014/08/04/aspect-oriented-programming-and-aranalytics/). Let me know if you have any questions.

**Comment by sdgandhi** [comment]
Great thank you! This is a beautifully written library regardless.

**Comment by ashfurrow** [comment]
Working on this now. Stay tuned!
