### ISSUE TITLE
[question] In ARDSL, why require that every page has a name?

### ISSUE THREAD

**Issue by cdzombak** [orta/ARAnalytics#123]
In our app, we configure some very coarse screen tracking via `ARDSL` with this code:

``` objc
ARAnalyticsTrackedScreens: @[
    @{
        ARAnalyticsClass: UIViewController.class,
        ARAnalyticsDetails: @[
            @{ ARAnalyticsPageNameKeyPath: @"title", }
        ],
    }
]
```

I noticed today that while debugging (assertions are disabled in our release builds), the app crashes on the following assertion, from line `26` or `ARDSL`: 

``` objc
pageName = [instance valueForKeyPath:pageNameKeypath] ?: @"";
NSAssert(pageName, @"Value for Key on `%@` returned nil from instance of class: `%@`", pageNameKeypath, NSStringFromClass([instance class]));
```

Why is this assertion here? Not every view controller has a title; would it not be better to fallback to some sane behavior (perhaps an empty string, or not logging the event, coupled with a warning `NSLog` call) instead of asserting this here?

**Comment by ashfurrow** [comment]
So after thinking this over, I think it makes sense to use the "should fire" block to specify only to fire if there is a non-`nil` `title`. I'll follow up in #125.
