### ISSUE TITLE
Add support for Snowplow

### ISSUE THREAD

**Issue by alexanderfabry** [orta/ARAnalytics#132]
We're using snowplow alongside other analytics tools like mixpanel -- would be great to have support for it in ARAnalytics.

http://snowplowanalytics.com/blog/2014/09/17/snowplow-ios-tracker-0.1.1-released/

**Comment by orta** [comment]
:+1:

**Comment by orta** [comment]
Waiting on https://github.com/snowplow/snowplow-ios-tracker/issues/100

**Comment by alexanderdean** [comment]
Thanks to Wunderlist, the new version of the Snowplow Tracker is now using NSURLSession (and has OS-X support too)...

**Comment by orta** [comment]
:star:

**Comment by orta** [comment]
I've added this :+1:

**Comment by alexanderdean** [comment]
Huge! This is cool @orta. (BTW no biggie but we are Snowplow not SnowPlow these days...)
