### ISSUE TITLE
Add Default subspec

### ISSUE THREAD

**Issue by sgtsquiggs** [orta/ARAnalytics#133]
I have a pod that depends on ARAnalytics. I don't want to depend on 'ARAnalytics' because it will pull in every subspec. Is there a way to depend on ARAnalytics without requiring the entire library or a specific subspec?

**Comment by ashfurrow** [comment]
Setting `ARAnalytics/CoreIOS` as a dependency should do it. Dunno if it's worth making it the default subspec generally, since it's such a specific use case.

**Comment by ashfurrow** [comment]
(Or `ARAnalytics/CoreMac`, as you like.)

**Comment by sgtsquiggs** [comment]
Works for me.
```ruby
s.osx.dependency 'ARAnalytics/CoreMac'
s.ios.dependency 'ARAnalytics/CoreIOS'
```

Linter fires off a few notes, but it still validates.

```
- NOTE  | [OSX] [xcodebuild]  ARAnalytics/ARNavigationControllerDelegateProxy.h:13:58: warning: cannot find protocol definition for 'UINavigationControllerDelegate'
- NOTE  | [OSX] [xcodebuild]  ARAnalytics/ARNavigationControllerDelegateProxy.m:21:24: warning: assigning to 'NSObject<UINavigationControllerDelegate> *__strong' from incompatible type '__strong id<UINavigationControllerDelegate>'
```

**Comment by sgtsquiggs** [comment]
Here's the pod for those interested. Bridges ARAnalytics and CocoaLumberjack.

https://github.com/sgtsquiggs/ARAnalyticsLogger

**Comment by ashfurrow** [comment]
The first problem is pretty esoteric – I wouldn't worry about it – and the second one is [the file](https://github.com/orta/ARAnalytics/blob/30f852dfe8890cb304e81e89ef5a4cd160cd4bb4/ARNavigationControllerDelegateProxy.h) missing `@import UIKit;`. We can fix that – I'll open some issues.

**Comment by ashfurrow** [comment]
Opened a PR: https://github.com/orta/ARAnalytics/pull/135

**Comment by orta** [comment]
Cool library @sgtsquiggs - think we can use this too :dancers:

**Comment by orta** [comment]
This is merged. Closing issue :+1:
