### ISSUE TITLE
duplicate references in build phase

### ISSUE THREAD

**Issue by 1aurabrown** [orta/ARAnalytics#142]
![screen shot 2015-03-23 at 11 49 58 am](https://cloud.githubusercontent.com/assets/3171662/6783905/d4187f34-d152-11e4-9f49-c30dafac3a6f.png)

**Comment by orta** [comment]
This should be fixed.

**Comment by orta** [comment]
No its not.

**Comment by orta** [comment]
:D

**Comment by banaslee** [comment]
Fixed? Hopefully this won't break anyone's build.

**Comment by orta** [comment]
👍

**Comment by orta** [comment]
Should be fixed in CP too now,
