### ISSUE TITLE
Add support for Swift 1.2

### ISSUE THREAD

**Issue by tomchify** [orta/ARAnalytics#147]
Hi there,

With the update to Swift 1.2 on 4/9/2015, it looks like ARAnalytics throws a few errors:

Undefined symbols for architecture arm64:
  "_kGAIScreenName", referenced from:
      -[GoogleAnalyticsProvider didShowNewPageView:] in GoogleAnalyticsProvider.o
  "_OBJC_CLASS_$_Crashlytics", referenced from:
      objc-class-ref in CrashlyticsProvider.o
     (maybe you meant: _OBJC_CLASS_$_CrashlyticsProvider)
  "_CLSLog", referenced from:
      -[CrashlyticsProvider event:withProperties:] in CrashlyticsProvider.o
      -[CrashlyticsProvider remoteLog:] in CrashlyticsProvider.o
  "_OBJC_CLASS_$_GAI", referenced from:
      objc-class-ref in ARAnalytics+GoogleAnalytics.o
      objc-class-ref in GoogleAnalyticsProvider.o
  "_OBJC_CLASS_$_GAIDictionaryBuilder", referenced from:
      objc-class-ref in ARAnalytics+GoogleAnalytics.o
      objc-class-ref in GoogleAnalyticsProvider.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Perhaps I have misconfigured something, but I think it's an issue with Swift 1.2. Thanks in advance.

**Comment by tomchify** [comment]
Ahh I spoke too soon. Perhaps it's an issue using "use_frameworks!" in the Podfile. Sorry.

**Comment by orta** [comment]
:+1:
