### ISSUE TITLE
NSInternalInconsistencyException when adding page tracking hook

### ISSUE THREAD

**Issue by TiagoVeloso** [orta/ARAnalytics#148]
I am using page tracking with the DSL feature in an iOS 8.3 simulator. I configure page tracking with the following configuration:

    @{
      ARAnalyticsTrackedScreens : @[@{
        ARAnalyticsClass : UIViewController.class,
        ARAnalyticsDetails : @[@{
          ARAnalyticsPageNameKeyPath : @"title",
        }],
        ARAnalyticsShouldFire : ^BOOL(UIViewController *controller, NSArray *parameters) {
          return controller.title != nil;
        }}]

But I am always getting the following error:

2015-04-17 11:48:41.938 Shoik[63892:872919] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Value for Key on `_title` returned nil.'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010abe5c65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010a87ebb7 objc_exception_throw + 45
	2   CoreFoundation                      0x000000010abe5aca +[NSException raise:format:arguments:] + 106
	3   Foundation                          0x00000001083d798f -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 195
	4   Shoik                               0x0000000106c2aeeb __53+[ARAnalytics(DSL) addScreenMonitoringAnalyticsHook:]_block_invoke_4 + 427
	5   Shoik                               0x0000000106d8455f -[RACSubscriber sendNext:] + 239
	6   Shoik                               0x0000000106d4659c -[RACPassthroughSubscriber sendNext:] + 444
	7   Shoik                               0x0000000106d83574 __23-[RACSubject sendNext:]_block_invoke + 68
	8   Shoik                               0x0000000106d83373 -[RACSubject enumerateSubscribersUsingBlock:] + 595
	9   Shoik                               0x0000000106d83507 -[RACSubject sendNext:] + 151
	10  Shoik                               0x0000000106d2d69b RACForwardInvocation + 347
	11  Shoik                               0x0000000106d2d47c __RACSwizzleForwardInvocation_block_invoke + 92
	12  CoreFoundation                      0x000000010ab42f4f ___forwarding___ + 495
	13  CoreFoundation                      0x000000010ab42cd8 _CF_forwarding_prep_0 + 120
	14  UIKit                               0x0000000109305ff1 -[UIViewController _setViewAppearState:isAnimating:] + 567
	15  UIKit                               0x0000000109306b3b -[UIViewController _executeAfterAppearanceBlock] + 52
	16  UIKit                               0x00000001091f562c _applyBlockToCFArrayCopiedToStack + 314
	17  UIKit                               0x00000001091f54c5 _afterCACommitHandler + 564
	18  CoreFoundation                      0x000000010ab18ca7 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	19  CoreFoundation                      0x000000010ab18c00 __CFRunLoopDoObservers + 368
	20  CoreFoundation                      0x000000010ab0ea33 __CFRunLoopRun + 1123
	21  CoreFoundation                      0x000000010ab0e366 CFRunLoopRunSpecific + 470
	22  GraphicsServices                    0x000000010b689a3e GSEventRunModal + 161
	23  UIKit                               0x00000001091d1900 UIApplicationMain + 1282
	24  Shoik                               0x0000000106b7016f main + 111
	25  libdyld.dylib                       0x000000010b10e145 start + 1

Am I doing something wrong?

**Comment by cdzombak** [comment]
This older issue/PR may provide context; but I am unsure if they'll be particularly helpful:

- https://github.com/orta/ARAnalytics/issues/123
- https://github.com/orta/ARAnalytics/pull/141

**Comment by pfleiner** [comment]
I just submitted a pull request (#153) fixing this. It looks like the function ```ar_shouldFireForInstance``` was being passed the dictionaries in the details array, so it could never find the block.

**Comment by ashfurrow** [comment]
@TiagoVeloso Can you verify what version of ARAnalytics you're using? This behaviour shouldn't be present in the current 3.0.

**Comment by pfleiner** [comment]
Ahh, I see what it is. @TiagoVeloso your ```ARAnalyticsShouldFire``` key value pair should be included in the dictionary contained in the array value for ```ARAnalyticsDetails```.

I didn't see that the details value was an array of dictionaries. For the screen tracking, at least, is there any particular reason why that is, apart from symmetry with the event tracking? Anyway, I'll close my pr.

**Comment by ashfurrow** [comment]
It's an array so you can have multiple "view" events for a single class, if you wanted to. Or maybe two events that fire exclusively (one or the other) based on the "should fire" block. Does that make sense?

**Comment by pfleiner** [comment]
Yeah, definitely. Thanks!

**Comment by TiagoVeloso** [comment]
I'm using version 3.0. I am now testing if the issue persists with `ARAnalyticsShouldFire ` inside `ARAnalyticsDetails ` dictionary. 

Sorry I didn't notice that bit. It seems to be working now.

PS: I feel dumb now :/

**Comment by ashfurrow** [comment]
@TiagoVeloso Hey! Don't feel dumb! This is an easy mistake to make, and one of the reasons @kylef suggested not relying on dictionaries/arrays, but rather using actual classes. I should have caught it when I first saw the issue, anyway. Cheers!

**Comment by TiagoVeloso** [comment]
Yeah, when using arrays of dictionaries it tends to get messy and harder to read at a glance. It's all working now :)

**Comment by TiagoVeloso** [comment]
Perhaps you could clarify in the example in the `README.md` file that `ARAnalyticsShouldFire` sould be in the `ARAnalyticsDetails` array. Just to make things clearer.

**Comment by ashfurrow** [comment]
Yeah, looks like it kind of "inlines" the dictionary. I'll switch.

**Comment by ashfurrow** [comment]
Cool, see #154. Input welcome!
