### ISSUE TITLE
Ignore file refers Podfile.lock but this is still in the repository

### ISSUE THREAD

**Issue by banaslee** [orta/ARAnalytics#161]
I guess this is because it is lacking the path ('Bootstrap/') but I'd assume it'd ignore all files named Podfile.lock regardless of the path.

**Comment by orta** [comment]
Thanks for the catch, a lockfile should always be in source control :+1: https://github.com/orta/ARAnalytics/commit/77d68652387edf271f0c28327da3dae354e49609
