### ISSUE TITLE
HockeyAppProvider: ‘breadcrumbs’ get logged but are not part of the crash reports

### ISSUE THREAD

**Issue by mr-v** [orta/ARAnalytics#166]
Hello,
Here's a bare minimum project in which I'm able to reproduce it: https://github.com/mr-v/CrashLoggingTest.
I'm using :head version of HockeySDK with support for `-[BITCrashDetails appProcessIdentifier]`. Added some logs of my own and it looks like no logged messages are found and issue is somewhere within `ARAnalyticalProvider`.

I know this feature is not officially supported yet, but initially I was able to get this data a few times. Now it doesn't work at all. Perhaps the issue is somewhere within my setup?

**Comment by alloy** [comment]
Didn’t see this until just know when I was wondering why it wasn’t working for us either :(

Will have to investigate.

**Comment by alloy** [comment]
Hmm, with your project it is working for me

```
2015-06-24 17:19:20.687 CrashLoggingTest[754:196283] messages: (
    "[2015-06-24 17:18:47.300] proccess id: 747",
    "[2015-06-24 17:18:55.495] 2015-06-24 15:18:55 +0000"
)
```

Something has to be wrong somewhere, though, as I’m not getting any breadcrumbs in our released app either. Can you tell me what exact steps you take to reproduce it with your project? I did:

1. Disable debugging in the scheme
2. Run on my device, hit ‘log’, and then let it crash
3. Enable debugging in the scheme
4. Run again on my device and see that the messages are retrieved from the logs

**Comment by alloy** [comment]
According to https://github.com/emaloney/CleanroomASL/#differences-between-the-device-and-simulator, it’s basically just unusable on device. It’s not entirely true, as I have been testing on device, but there’s clearly conditions under which it doesn’t work, so it’s not trustable at the least.

Will log to disk after all and assume that log file rotation isn’t a real big problem.

**Comment by alloy** [comment]
Ok, scratch that, I found the issue and it was a silly one… See #185.
