### ISSUE TITLE
+setupWithAnalytics contains some disreputable code additions

### ISSUE THREAD

**Issue by cbowns** [orta/ARAnalytics#170]
I noticed this small probable issue in [ARAnalytics.m](https://github.com/orta/ARAnalytics/blob/f44089c84a25d168f770569da3cfa7ec6c35bd22/ARAnalytics.m#L139) when working on a forthcoming integration: 

```
    // Crashlytics / Crittercism should stay at the bottom of this,
    // as they both need to register exceptions, and you'd only use one.

    if (analyticsDictionary[ARCrashlyticsAPIKey]) {
        [self setupCrashlyticsWithAPIKey:analyticsDictionary[ARCrashlyticsAPIKey]];
    }
    if (analyticsDictionary[ARFabricKits]) {
        [self setupFabricWithKits:analyticsDictionary[ARFabricKits]];
    }
…
```

That chunk is followed by five other integrations which were presumably dropped in after Crashlytics/Fabric and Crittercism. Should they be moved up? (Probably.) (Want a PR for this?)

**Comment by orta** [comment]
Yeah, best move them back to the bottom, and yeah, a PR'd be nice.
