### ISSUE TITLE
HockeySDK 3.7.0

### ISSUE THREAD

**Issue by jhersh** [orta/ARAnalytics#180]
Ahoy! I thought we might discuss how best to handle [today's HockeySDK update](http://hockeyapp.net/help/sdk/ios/3.7.0/docs/docs/Changelog.html) in ARAnalytics. 

In short:

- The existing `HockeySDK` spec now offers two subspecs (`HockeySDK/CrashOnlyLib` and `HockeySDK/AllFeaturesLib`), both of which are now distributed as dynamic frameworks. ARAnalytics' Hockey subspec still points to this spec, but ARAnalytics now fails to build because `#import <HockeySDK/HockeySDK.h>` no longer matches any file in the new Hockey framework.
- Hockey has added a second `HockeySDK-Source` spec with 7(!) subspecs, which allow you to pick and choose Hockey features, and all of which are built from source (i.e. not dynamic frameworks)

The simplest, most minimal change for ARAnalytics is probably to switch entirely to the new `HockeySDK-Source` spec, which should fix ARAnalytics to once again build properly without any other changes.

A slightly more involved change might be to add new ARAnalytics subspecs, perhaps one for `HockeySDK` and one for `HockeySDK-Source`, to allow the developer to choose as appropriate. ARAnalytics' Hockey provider will need to detect which spec is used and import Hockey files appropriately.

An even more involved change might require some mapping between ARAnalytics subspecs and Hockey's new feature subspecs, to allow for the most developer control over which files are imported.

**Comment by orta** [comment]
Interesting, I think HockeySDK-Source is the way to go for the default as current. I also think it makes sense to have the second subspec that is the framework build too. I also wonder about maybe having a version that doesn't import the dependency, and lets you do that yourself ala Crashlytics. Then you can do any combination of subspecs for hockey.

**Comment by alloy** [comment]
Following up on this, doesn’t the HockeyApp provider really only need the `HockeySDK-Source/CrashReporter` and `HockeySDK-Source/AdHocUpdates` subspecs?

**Comment by orta** [comment]
Yeah, but to not break backwards compatibility I think all is fine ATM
