### ISSUE TITLE
HockeyAppOSX integration is broken; build fails

### ISSUE THREAD

**Issue by natan** [orta/ARAnalytics#187]
Currently, adding the `HockeyAppOSX` subspec causes build to fail: the import paths in `HockeyAppProvider.m` are incorrect, and once those are fixed there are a number of other build failures due to SDK differences in `HockeySDK-iOS` and `HockeySDK-Mac`. It seems the best solution to this is to separate the two providers out so that both build properly. I'm happy to take that task on in the next couple days!

**Comment by orta** [comment]
Sure thing, thanks @natan
