### ISSUE TITLE
GoogleAnalytics-iOS-SDK has been deprecated in favor of GoogleAnalytics

### ISSUE THREAD

**Issue by glentregoning** [orta/ARAnalytics#200]
When pod installing the latest ARAnalytics version with the 'GoogleAnalytics' podspec I receive the warning 

`[!] GoogleAnalytics-iOS-SDK has been deprecated in favor of GoogleAnalytics` 

It looks like Google has a new pod 'GoogleAnalytics' which should be used going forward.

**Comment by orta** [comment]
agree, yeah, they've made an official pod, would love to see a PR? ( I don't use GA in any of our apps )

**Comment by pietbrauer** [comment]
Fixed with #201
