### ISSUE TITLE
podspec should allow for Mac OS X use of Fabric provider

### ISSUE THREAD

**Issue by levigroker** [orta/ARAnalytics#214]
There is no reason to exclude Mac OS from the use of the Fabric provider, and with the current podspec there's no way to use Fabric with ARAnalytics on Mac OS.

Adding "fabric_osx" as a subspec is one option. :)

**Comment by orta** [comment]
Sure! I'll happily take a PR adding it :dancers:

**Comment by levigroker** [comment]
Not sure is it an issue any longer.
