### ISSUE TITLE
Pod uses the deprecated version of Flurry

### ISSUE THREAD

**Issue by igrekde** [orta/ARAnalytics#217]
Hi! Thanks for a great analytics library - it's very fun and easy to use!

It seems that you're using a deprecated version of **Flurry SDK**:

**My Podfile**:
```
pod 'ARAnalytics', '~> 3.8', :subspecs => ["Flurry"]
```

**Console output**:
```
Using ARAnalytics (3.8.0)
Using FlurrySDK (6.7.0)
...
Using FlurrySDK (6.7.0) [!] FlurrySDK has been deprecated in favor of Flurry-iOS-SDK
```

Am I doing something wrong?

**Comment by orta** [comment]
You might need to do a `pod update ARAnalyics`or `ARANalytics/Flurry` - we now point to the new Flurry library: https://github.com/orta/ARAnalytics/blob/master/ARAnalytics.podspec#L17

**Comment by orta** [comment]
ah it's not been shipped yet, and I'm flying most of today, you'll need to use `:head` to use the latest master

**Comment by igrekde** [comment]
@orta Thanks a lot for your help!

**Comment by MigrantP** [comment]
I'm trying to get this to switch to Flurry-iOS-SDK, but it refuses to do so. I've been using ARAnalytics for a while, and nothing I try will make it switch away from FlurrySDK.

The Podfile says:
pod 'ARAnalytics', :head, :subspecs => ["Flurry"]

pod install, pod update, pod update ARAnalytics, pod update ARAnalytics/Flurry, all have the same result - FlurrySDK stays. Deleting all the pods and running pod install, Flurry SDK comes back.. I tried cleaning the cache, it still comes back.

I'm on CocoaPods 0.39.0.

**Comment by orta** [comment]
Hrm, you could try deleting the ARAnalyitcs / FlurrySDK line in your podfile.lock which should re-trigger a force lookup.

Other option is to try `pod update ARAnalytics FlurrySDK` I'm not too sure how to trigger the resolver to ignore the dependency on Flurry and allow updating to another.

**Comment by MigrantP** [comment]
No luck. I even tried completely removing CocoaPods from the project and doing a fresh init/install, no luck.

I tried making a brand new test project. Did pod init, and added this to the Podfile:
pod 'ARAnalytics', :head, :subspecs => ["Flurry"]

And pod install does:

Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Installing ARAnalytics (HEAD based on 3.8.0)
Installing FlurrySDK (6.7.0)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `Test.xcworkspace` for this project from now on.
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 2 total pods installed.

[!] FlurrySDK has been deprecated in favor of Flurry-iOS-SDK

**Comment by orta** [comment]
Ah! OK
So, this is my fault, sorry! So `:head` uses the trunk podspec, and the latest commit. I've pushed a release anyway, but I should have been recommending just using `:git =>"https://github.com/orta/ARAnalytics.git"`

**Comment by MigrantP** [comment]
That worked, thanks! I'll switch it back to using the specs repo again.
