### ISSUE TITLE
setupAppsFlyerWithAppID missing from ARAnalytics.h

### ISSUE THREAD

**Issue by AdamBCo** [orta/ARAnalytics#234]
Is setupAppsFlyerWithAppID suppose to be missing from ARAnalytics.h? Why was it removed?

**Comment by orta** [comment]
I don't know if it was ever added, it's been missing all year: https://github.com/orta/ARAnalytics/blob/3.0.0/ARAnalytics.h

**Comment by orta** [comment]
Coming due to lack of a reply, doing an issues cleanup. You're welcome to add it :dancers: !
