### ISSUE TITLE
Flurry Capture Event Duration?

### ISSUE THREAD

**Issue by kidsid49** [orta/ARAnalytics#235]
In flurry docs 
https://developer.yahoo.com/flurry/docs/analytics/gettingstarted/events/ios/
We can capture particular even duration but in ARAnalytics.h there is  no such function that wraps up
[Flurry endTimedEvent:@"Article_Read" withParameters:nil]; 

I went through the "FlurryProvider.h" and didn't find any usages of "endTimedEvent" method so was just curious how ARAanalytics predict the ending of timed event?

**Comment by orta** [comment]
I think it does it by using the subclass' method for ending the timed event

**Comment by orta** [comment]
Coming due to lack of a reply, doing an issues cleanup.
