### ISSUE TITLE
How to intercom custom user track sdk using your spi?

### ISSUE THREAD

**Issue by ivanyang1984** [orta/ARAnalytics#241]
In our company, we are now using the custom user track sdk(that was written our own), we want to use ar as spi to   decouple the  concrete ut implemention with its interface.    Could you please provide any guideline about this?

**Comment by orta** [comment]
Create an ARAnalyticsProvider subclass, e.g. [https://github.com/artsy/energy/blob/master/Classes/Util/Debugging/ARIntercomProvider.m](ARIntercomProvider.m) and [pass it into ARAnalytics](https://github.com/artsy/energy/blob/master/Classes/Util/Debugging/ARAnalyticsHelper.m#L42-L46)

:+1: it will receive all the normal callbacks
