### ISSUE TITLE
Release v3.9.1

### ISSUE THREAD

**Issue by pietbrauer** [orta/ARAnalytics#258]
Some of the changes in the current master are crucial, e.g. `GoogleAnalytics` now [has Bitcode support](https://github.com/orta/ARAnalytics/commit/8ea7e9fbf5263e862e54f150dcb1c7d805bbc8c5). It is also 2 months since the last release was made.

Any chance you could release version 3.9.1?

Changeset: https://github.com/orta/ARAnalytics/compare/3.9.0...master

**Comment by orta** [comment]
:+1: alright, should be pushed - thanks for the reminder


![screen shot 2016-03-09 at 3 04 09 pm](https://cloud.githubusercontent.com/assets/49038/13648737/3a713b20-e608-11e5-962c-21db8f6056e6.png)
