### ISSUE TITLE
Import error with Localytics

### ISSUE THREAD

**Issue by cemaleker** [orta/ARAnalytics#277]
Are there any specific reason why ARAnalytics uses 

    #import "Localytics.h"

to import Localytics instead of 

    @import Localytics;

I am getting import error while compiling with the current import method. I have fixed that on my fork and I want to send out a pull request if there is no specific reason.

**Comment by orta** [comment]
Not to my knowledge

**Comment by BenchR267** [comment]
https://github.com/orta/ARAnalytics/pull/278
