### ISSUE TITLE
Remove TestFlight events

### ISSUE THREAD

**Issue by kylef** [orta/ARAnalytics#70]
TestFlight have removed FlightPath analytics since Apple bought them, there is no where on the website to view the analytics so I think it's time they are removed from ARAnalytics.

Do we want to remove TestFlight completely from ARAnalytics? Or just remove the events being sent (so you can still `[TestFlight takeOff:identifier]`).

**Comment by patoroco** [comment]
I just receive an email after try to upload a new version of an existent app with pod ARAnalytics/TestFligtht:
> Dear developer,
> We have discovered one or more issues with your recent delivery for "myapp". Your delivery was successful, but you may wish to correct the following issues in your next delivery:
> TestFlight SDK - TestFlight no longer requires an SDK to enable beta testing. To continue using TestFlight, set up Beta Testing in iTunes Connect and remove references to the TestFlight SDK from the following executables: myapp.app/myapp
> After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to iTunes Connect.
> Regards,
> The App Store team


I going to remove it from my project because currently we are using crashlytics for this subject, but only in advise :)

**Comment by orta** [comment]
Thanks!
